server: 
  port: 3344 
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thinkingpi9/msc-Demo.git #GitHub上面的git仓库名字
          username: felix.fu@qq.com
          password: qq17143101
          searchPaths: config
 
#logging:
  #level:
    #root: DEBUG
